### ISSUE TITLE
Live update route (see note)

### ISSUE THREAD

**Issue by wdamon** [LintLions/Respondr#50]

**Comment by jennyxcheng** [comment]
Set timeout every 10 second query Google API with beacon responder locations to redraw route

**Comment by jennyxcheng** [comment]
component mount - master set interval that always updates my locations (geo watch function). If I'm not assigned a responder, get nearby responders. If i'm assigned a responder, every 10 second get responder information and update the route. Same thing for responder who is assigned a beacon.
